### ISSUE TITLE
Compatibility with strong parameters and many to many relationships

### ISSUE THREAD

**Issue by jamesla** [equivalent/public_uid#19]
I was wondering if there was a way to make this awesome gem work with rails built in strong params and many to many relationship handling so that we get a bit of rails magic in terms of updating models.

Currently I use this rails shorthand way to create a car and associate it with brands, this works great and short hands like these are one of the reasons I love working with rails.

```
def food_params
  params.require(:cars).permit(:name, ingredient_ids: [])
end
```

However when I try:

```
def food_params
  params.require(:cars).permit(:name, ingredient_public_uids: [])
end
```

I get `ActiveModel::UnknownAttributeError (unknown attribute 'ingredient_public_uids' for Food.):` there's not a lot of information on the rails docs on how this works and this gem doesn't mention it.

Is what I'm trying to do possible with this gem?

**Comment by equivalent** [comment]
hi @jamesla thank you for question

I see what you are trying to do here (be able to associate has many records based on public_uids instead of ids) 

I assume you have

```
class Car < ApplicationRecord
  has_many :ingredients
end
```

with the `has_many` Rails will insert bunch of methods to your `Car` model/class such as `ingredients` and `ingredient_ids` 

so therefore you are able to do 

```ruby
car = Car.create(name: 'car')
car.ingredients  << Ingredient.create
car.ingredients  << Ingredient.create
car.ingredients
# => [<#Ingredient>, <#Ingredient>]
```

but also


```ruby
car = Car.create(name: 'car')
i1 = Ingredient.create
i2 = Ingredient.create
car.ingredient_ids = [i1.id, i2.id]
car.save

car.ingredients
# => [<#Ingredient>, <#Ingredient>]
```

and therefore you are able to use Rails Strong params in Controller

```
  params.require(:cars).permit(:name, ingredient_ids: [])
```

because the strong params assumes you have method `ingredient_ids=` 


So you are right in a sense that `public_uid` gem should **ideally** extend `ActiveRecord` (Rails) so that on any `has_many` call  a `_ids`, `_ids=` and `_uids`, `_uids=` method is added to the model (so therefore in your case  `ingredient_public_uids=`) 

So I'll definitely consider this feature in future release, however at this point I don't have time to built in this feature myself. PR is welcome from anyone :trophy:  (just heads up main complication is that developer can define "custom field" for public id )

> To be honest this is first time I thought about it. Nice point and great suggestion :+1: 

### Solution in meantime

Something like this should work:

```ruby
class Car < ApplicationRecord
  has_many :ingredients

  def ingredient_public_uids=(public_uids)
    ingredients = public_uids.map { |uid| Ingredient.find_puid(uid) }
  end

  def ingredient_public_uids
    ingredients.map(&:public_uids)
  end
end
```
controller:
```
# a/c/ingredients_controller.rb

# ...
    params.require(:cars).permit(:name, ingredient_public_uids: [])
# ...
```

**Comment by jamesla** [comment]
Ok great what an awesome writeup have implemented that and it's working. Thanks @equivalent
